name: Create and optionally publish a release

inputs:
  token:
    description: "GitHub access token"
    type: "string"
    required: true

  node-version:
    description: "Node version"
    type: "string"
    required: false
    default: "18.x"

  restore-build:
    description: "Retrieve the build artifact for this commit"
    type: "boolean"
    required: false
    default: true

  draft:
    description: "Create a draft release (default: true)"
    type: "boolean"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://registry.npmjs.org"

    - name: Connect dependency cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json', 'package.json') }}

    - uses: actions/download-artifact@v3
      if: inputs.restore-build
      with:
        name: build-${{ github.sha }}

    - name: Compile release template
      working-directory: .github
      run: |
        touch release.md
        mkdir -p dist
        touch dist/title.txt
        echo $tag > dist/title.txt
        cp release.md dist/
        npm run build:release --if-present
      shell: bash

    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        gh release create "${{ github.ref_name }}" \
          ${{ inputs.draft && '--draft' || '' }} \
          --repo "$GITHUB_REPOSITORY" \
          --title "$(< "$GITHUB_WORKSPACE/.github/dist/title.txt")" \
          --notes-file "$GITHUB_WORKSPACE/.github/dist/release.md"
      shell: bash
